-- MySQL Script generated by MySQL Workbench
-- 04/22/14 01:51:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema groopmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groopmate` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `groopmate` ;

-- -----------------------------------------------------
-- Table `groopmate`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`users` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `facebook_id` VARCHAR(100) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`groups` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`group_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`group_members` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`group_members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `group_idx` (`group_id` ASC),
  CONSTRAINT `user_idk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `groopmate`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_idk1`
    FOREIGN KEY (`group_id`)
    REFERENCES `groopmate`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`quizzes` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`quizzes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NOT NULL,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idk_idx` (`user_id` ASC),
  INDEX `group_idk_idx` (`group_id` ASC),
  CONSTRAINT `user_idk3`
    FOREIGN KEY (`user_id`)
    REFERENCES `groopmate`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_idk`
    FOREIGN KEY (`group_id`)
    REFERENCES `groopmate`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`quiz_taken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`quiz_taken` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`quiz_taken` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_idx` (`quiz_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `user_idk4`
    FOREIGN KEY (`user_id`)
    REFERENCES `groopmate`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `quiz_idk2`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `groopmate`.`quizzes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`quiz_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`quiz_results` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`quiz_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `score` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `completed` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idk_idx` (`user_id` ASC),
  INDEX `quiz_idk_idx` (`quiz_id` ASC),
  CONSTRAINT `user_idk2`
    FOREIGN KEY (`user_id`)
    REFERENCES `groopmate`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `quiz_idk1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `groopmate`.`quizzes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`notifications` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actor` INT NOT NULL,
  `subject` INT NULL,
  `object` INT NULL,
  `seen` TINYINT NULL,
  `type` VARCHAR(20) NULL COMMENT 'INV - invitation to join group' /* comment truncated */ /*QUIZ - quiz created by someone
*/,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`quiz_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`quiz_questions` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`quiz_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NOT NULL,
  `quiz_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_idk_idx` (`quiz_id` ASC),
  CONSTRAINT `quiz_idk3`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `groopmate`.`quizzes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groopmate`.`quiz_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groopmate`.`quiz_options` ;

CREATE TABLE IF NOT EXISTS `groopmate`.`quiz_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NOT NULL,
  `correct` TINYINT NOT NULL,
  `question_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `question_idk_idx` (`question_id` ASC),
  CONSTRAINT `question_idk`
    FOREIGN KEY (`question_id`)
    REFERENCES `groopmate`.`quiz_questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
